spring.application.name=car-rental-project
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgres
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=TRACE
logging.level.org.springframework.security.web=DEBUG


jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.accessExpirationMs=900000
jwt.refreshExpirationMs=604800000
